### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ujosatXyZ** [payu-intrepos/payu-non-seamless-react#1]
I tried to integrate this code with my project.
Test card payment was succeed.After success it's redirect to that url and crash the app ios.
But android shows the credentials is invalid.
Could you share the flow?

**Comment by himgupta229** [comment]
> I tried to integrate this code with my project.
> Test card payment was succeed.After success it's redirect to that url and crash the app ios.
> But android shows the credentials is invalid.
> Could you share the flow?

Can you share the integration file? or you can reach out to mobile.integration@payu.in

**Comment by rajmaxi** [comment]
Hi, i tried to integrate payu non seam less react.. when i download your code to check integration process, iam getting error on click button.. "Type should be of netbanking or upi/ wallet ".. can you please help me

**Comment by Vaibhavshyoran** [comment]
> Hi, i tried to integrate payu non seam less react.. when i download your code to check integration process, iam getting error on click button.. "Type should be of netbanking or upi/ wallet ".. can you please help me

Hi rajmaxi,

Use  paymentModesOrder: [{ 'UPI': 'TEZ' }, { 'Wallets': 'PAYTM' }], in payUCheckoutProConfig then  check.
