### ISSUE TITLE
Could not resolve all artifacts (phonepe.intentsdk.android.release:IntentSDK:0.1.5.4)

### ISSUE THREAD

**Issue by Navhal111** [payu-intrepos/payu-non-seamless-react#17]
Hey, I am using version 2.1.0 of payu-non-seam-less-react,
after installation, it shows me the 403 from the server. I am not able to run the app ...

Check more info check the image:- https://i.stack.imgur.com/5i9kX.png

Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not download IntentSDK-0.1.5.4.aar (phonepe.intentsdk.android.release:IntentSDK:0.1.5.4)
      > Could not get resource 'https://phonepe.bintray.com/PhonePeIntentSDK/phonepe/intentsdk/android/release/IntentSDK/0.1.5.4/IntentSDK-0.1.5.4.aar'.
         > Could not GET 'https://phonepe.bintray.com/PhonePeIntentSDK/phonepe/intentsdk/android/release/IntentSDK/0.1.5.4/IntentSDK-0.1.5.4.aar'. Received status code 403 from server: [Forbidden](url)

**Comment by sachinxagrawal** [comment]
I am getting the same issue

**Comment by Navhal111** [comment]
> I am getting the same issue with version 2.2.0

i solved try this integration its solved new version 
https://payumobile.gitbook.io/sdk-integration/react-native/integration/integration

Add in Build.gradle
