### ISSUE TITLE
{"errorCode": "5014", "errorMsg": "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"}

### ISSUE THREAD

**Issue by ubaidjs** [payu-intrepos/payu-non-seamless-react#3]
I am getting this error after properly generating hash and passing it to payUPaymentParams object.

`{"errorCode": "5014", "errorMsg": "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"}`

**Comment by rajmaxi** [comment]
I am getting this same error 

{"errorCode": "5014", "errorMsg": "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"}

kindly do the need ful

**Comment by doneravelil** [comment]
Got similar issue. How did u fix that @ubaidjs @rajmaxi

**Comment by Basavaraddi3522** [comment]
Yes even I got same issue. Please help in fixing that @ubaidjs @rajmaxi @devDonovan

**Comment by shahfaizalc** [comment]
@Basavaraddi3522  @devDonovan  @rajmaxi kindly use the latest release of our releases 
https://mvnrepository.com/artifact/in.payu. Kindly reach us back if you still face the issue.

**Comment by ritaVaja** [comment]
I am getting this error after properly generating hash and passing it to payUPaymentParams object.

"errorCode": "5014", "errorMsg": "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"
please give solution @ubaidjs @rajmaxi @devDonovan
