### ISSUE TITLE
payu-non-seam-less-react:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by arihantop** [payu-intrepos/payu-non-seamless-react#54]
node_modules/payu-non-seam-less-react/android/build/generated/source/buildConfig/debug/com/payubiz/BuildConfig.java:13: error: variable VERSION_NAME is already defined in class BuildConfig
  public static final String VERSION_NAME = "3.0.0";

**Comment by imchintan** [comment]
![Screenshot 2023-01-10 at 4 36 42 PM](https://user-images.githubusercontent.com/17006735/211535484-bb36ed27-573d-4655-b19b-de638d4e81ba.png)
Remove line no: 13 from BuildConfig.java and try again.

**Comment by shahfaizalc** [comment]
kindly connect to us at mobile.integration@payu.in. will help you on this
