### ISSUE TITLE
Not working with android with Gradle Version 7.x

### ISSUE THREAD

**Issue by brokenpieworld** [payu-intrepos/payu-non-seamless-react#57]
While its working fine with iOS, but getting error in android as below:

`Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'maven' not found.`

If we manually update maven to `apply plugin: 'maven-publish'` getting another error:

` Configuration with name 'compile' not found.`

React Native Version 70.6
Gradle Version 7.x
Compile SDK version 33

**Comment by vikasis4** [comment]
getting the same error
