### ISSUE TITLE
Google play compliance issue because of com.minkasu:minkasu-2fa 

### ISSUE THREAD

**Issue by nateshmbhat** [payu-intrepos/payu-non-seamless-react#64]
Facing same issue as https://github.com/payu-intrepos/PayUCheckoutPro-Flutter/issues/18

**Comment by ShubhGar** [comment]
@nateshmbhat we are working on same and will release fix asap.

**Comment by shahfaizalc** [comment]
Kindly update to the latest version released. The issue has been addressed.
Thanks for reaching out to us.

**Comment by nateshmbhat** [comment]
thanks for the quick resolution 🙏. will update and check

**Comment by nateshmbhat** [comment]
i don't see com.minkasu dependency in this now. looks like this is resolved 👍🏻 Thanks :)

**Comment by shahfaizalc** [comment]
Hope all your payment modes working fine.

**Comment by nateshmbhat** [comment]
thanks
