### ISSUE TITLE
{"errorCode": "null", "errorMsg": "get_checkout_details Hash cannot be null or empty"}

### ISSUE THREAD

**Issue by ubaidjs** [payu-intrepos/payu-non-seamless-react#7]
I am getting this error after initiating payu screen. Everything work fine on ios through same code, but not on android.

react native version: 0.64.0
payu-non-seamless version: 2.2.0

**Comment by himgupta229** [comment]
Can you share code snippet how are you generating hash? Kindly override  generateHash callback as mentioned here[](https://keys.openpgp.org/search?q=41921FC2960C48B275659CC09CF16442656698AC)

**Comment by himgupta229** [comment]
Kindly override the method "generateHash" as mentioned here[](https://payumobile.gitbook.io/sdk-integration/react-native/integration/integration#5-handle-the-payment-completion-mandatory-step)
