### ISSUE TITLE
Exception thrown while executing UI block: -[__NSCFType CGColor]: unrecognized selector sent to instance 0x6000010aaee0

### ISSUE THREAD

**Issue by aman246810** [payu-intrepos/payu-non-seamless-react#8]
Exception thrown while executing UI block: -[__NSCFType CGColor]: unrecognized selector sent to instance 0x6000010aaee0

**Comment by LudinaReema** [comment]
@aman246810 I got the same error in iOS build. Can you plz let me know about the fix?

**Comment by airtelshivam** [comment]
Check your code, may be your UIView extension is conflicting with React Native extensions. In our case we our overriding borderColor

**Comment by imchintan** [comment]
I am facing the same error
Exception thrown while executing UI block: -[__NSCFType CGColor]: unrecognized selector sent to instance 0x600003493420
